services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: alunos_user
      POSTGRES_PASSWORD: alunos_password
      POSTGRES_DB: alunos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    

  api:
    image: c216-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://alunos_user:alunos_password@db:5432/alunos_db
    depends_on:
      - db

  tests:
    image: c216-api
    build: .
    volumes:
      - .:/app
    command: pytest tests/ -v
    depends_on:
      - db

volumes:
  postgres_data: